Repository neinteractiveliterature/intercode, pull requests merged in 2023-01, with the labels that each got.

#7315 Fix CORS issues caused by cache fix.
  script/genNginxNocache.js
Labels: org-consequences, patch

#7322 Don't query for the event details twice
  app/javascript/EventsApp/EventPage/index.tsx
Labels: frontend, performance, patch

#7337 Fix JWT generation
  config/initializers/doorkeeper.rb
Labels: bug, patch

#7338 Fix product image cloning
  app/services/content_cloners/content_cloner_base.rb
  app/services/content_cloners/store_content_cloner.rb
Labels: bug, patch

#7352 Precompile bootsnap cache for faster startup
  Dockerfile
Labels: performance, patch
